# Имя Workflow
name: 'API: Создать Issue для модерации'

# Триггер: внешний API-вызов от Vercel
on:
  repository_dispatch:
    types: [create-moderation-issue]

# Задачи
jobs:
  create-moderation-issue:
    name: 'Создание Issue для модератора'
    runs-on: ubuntu-latest

    # --- Безопасность: Права доступа ---
    # Workflow нужно право только на создание Issue. Доступ к коду не требуется.
    permissions:
      issues: write

    steps:
      # --- Единственный шаг: Создание GitHub Issue ---
      # Использует данные, полностью подготовленные на стороне Vercel.
      - name: Create GitHub Issue
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.client_payload.title;
            const body = context.payload.client_payload.body;

            if (!title || !body) {
              core.setFailed('Ошибка: Поля "title" или "body" отсутствуют в client_payload.');
              return;
            }

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `На модерацию: ${title}`,
              body: body,
              labels: ['new-prompt', 'needs-review']
            });