name: 'Уведомление о новом Pull Request'

on:
  pull_request:
    types: [opened] # Запускать только при создании нового PR

jobs:
  send-telegram-notification:
    name: 'Отправка уведомления в Telegram'
    runs-on: ubuntu-latest

    steps:
      - name: 'Формирование сообщения и отправка запроса'
        run: |
          # --- ИСПРАВЛЕНИЕ: Используем синтаксис EOF для безопасного создания JSON ---
          # 1. Формируем Markdown-сообщение
          MESSAGE_MARKDOWN="✅ *Новый Pull Request на модерацию!*\n\n*Название:* ${{ github.event.pull_request.title }}\n*Автор:* ${{ github.event.pull_request.user.login }}\n\n[Посмотреть PR на GitHub](${{ github.event.pull_request.html_url }})"

          # 2. Создаем JSON-payload, используя heredoc
          # Это гарантирует, что все спецсимволы и переносы строк будут обработаны корректно
          JSON_PAYLOAD=$(cat <<EOF
          {
            "message": "$MESSAGE_MARKDOWN"
          }
          EOF
          )

          # 3. Отправляем POST-запрос с готовым JSON
          curl --request POST \
            --url '${{ secrets.VERCEL_NOTICE_URL }}' \
            --header 'Content-Type: application/json' \
            --data "$JSON_PAYLOAD"