name: Create App Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Укажите тег для релиза приложения (например, v1.2.3)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      tag_name: ${{ steps.get_tag.outputs.name }}
    steps:
      - name: Determine Tag Name
        id: get_tag
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            TAG_NAME="${{ github.ref_name }}"
          else
            TAG_NAME="${{ github.event.inputs.tag }}"
          fi
          echo "name=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag.outputs.name }}
          release_name: App Release ${{ steps.get_tag.outputs.name }}
          body: "Сборка приложения Prompt Manager версии ${{ steps.get_tag.outputs.name }}."
          draft: false
          prerelease: ${{ contains(steps.get_tag.outputs.name, '-') }}

  build_assets:
    name: Build App for ${{ matrix.os }}
    needs: create_release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-14, ubuntu-22.04]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Linux prerequisites for AppImage
      - name: Install AppImage prerequisites (Linux only)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          # libfuse2: нужен многим AppImage рантаймам
          sudo apt-get install -y libfuse2 fuse3
          # удобные утилиты диагностики (необязательно)
          sudo apt-get install -y patchelf

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # Unified names
      - name: Set Asset Names (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          echo "ASSET_NAME=PromptManager-${{ needs.create_release.outputs.tag_name }}-windows-x64" >> $env:GITHUB_ENV
          echo "APP_NAME=PromptManager" >> $env:GITHUB_ENV

      - name: Set Asset Names (macOS)
        if: matrix.os == 'macos-14'
        shell: bash
        run: |
          echo "ASSET_NAME=PromptManager-${{ needs.create_release.outputs.tag_name }}-macos-$(uname -m)" >> $GITHUB_ENV
          echo "APP_NAME=PromptManager" >> $GITHUB_ENV

      - name: Set Asset Names (Linux)
        if: matrix.os == 'ubuntu-22.04'
        shell: bash
        run: |
          echo "ASSET_NAME=PromptManager-${{ needs.create_release.outputs.tag_name }}-linux-x86_64.AppImage" >> $GITHUB_ENV
          echo "APP_NAME=PromptManager" >> $GITHUB_ENV

      # Build binaries
      - name: Build with PyInstaller (Windows/macOS)
        if: matrix.os == 'windows-latest' || matrix.os == 'macos-14'
        run: pyinstaller --name "${{ env.APP_NAME }}" --onefile --windowed --paths ./src src/main.py

      - name: Build with PyInstaller (Linux)
        if: matrix.os == 'ubuntu-22.04'
        run: pyinstaller --name "${{ env.APP_NAME }}" --onefile --noconfirm --windowed --paths ./src src/main.py

      # Package to AppImage on Linux without requiring FUSE at runtime on the runner
      - name: Build AppImage (Linux only)
        if: matrix.os == 'ubuntu-22.04'
        shell: bash
        run: |
          # 1) Скачать linuxdeploy (исправлены ссылки)
          wget -q https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage -O linuxdeploy.AppImage
          chmod +x linuxdeploy.AppImage

          # 2) Подготовить AppDir структуру (без повторной сборки PyInstaller)
          mkdir -p AppDir/usr/bin
          cp dist/${{ env.APP_NAME }} AppDir/usr/bin/
          chmod +x AppDir/usr/bin/"${{ env.APP_NAME }}"

          # 3) Desktop-файл в корень AppDir (упрощенный подход)
          cat > AppDir/${{ env.APP_NAME }}.desktop << 'EOF'
          [Desktop Entry]
          Name=Prompt Manager
          Exec=${{ env.APP_NAME }}
          Icon=icon
          Type=Application
          Categories=Utility;
          EOF

          # 4) Иконка в корень AppDir
          cp assets/icon.png AppDir/icon.png

          # 5) Создание AppImage без дополнительных плагинов
          APPIMAGE_EXTRACT_AND_RUN=1 ./linuxdeploy.AppImage \
            --appdir AppDir \
            --executable AppDir/usr/bin/"${{ env.APP_NAME }}" \
            --desktop-file AppDir/"${{ env.APP_NAME }}".desktop \
            --icon-file AppDir/icon.png \
            --output appimage

          # 6) Переименование и права доступа
          mv ./*x86_64.AppImage "${{ env.ASSET_NAME }}"
          chmod +x "${{ env.ASSET_NAME }}"

          # 7) Проверка создания файла
          ls -la "${{ env.ASSET_NAME }}" || echo "AppImage не создан!"

      # Archive and upload
      - name: Archive built artifact (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: Compress-Archive -Path dist/${{ env.APP_NAME }}.exe -DestinationPath ${{ env.ASSET_NAME }}.zip

      - name: Archive built artifact (macOS)
        if: matrix.os == 'macos-14'
        run: zip -r ${{ env.ASSET_NAME }}.zip dist/"${{ env.APP_NAME }}.app"

      - name: Upload Release Asset (Windows/macOS)
        if: matrix.os == 'windows-latest' || matrix.os == 'macos-14'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./${{ env.ASSET_NAME }}.zip
          asset_name: ${{ env.ASSET_NAME }}.zip
          asset_content_type: application/zip

      - name: Upload Release Asset (Linux)
        if: matrix.os == 'ubuntu-22.04'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./${{ env.ASSET_NAME }}
          asset_name: ${{ env.ASSET_NAME }}
          asset_content_type: application/x-appimage
