# ==============================================================================
# GitHub Workflow: Обновление "живого" архива с промптами
# ==============================================================================
# Этот воркфлоу следит за изменениями в папке `prompts` и автоматически
# обновляет один-единственный "живой" релиз с тегом `latest-prompts`.
#
# Приложение обращается к этому релизу для получения самой свежей
# библиотеки промптов.
#
# --- ТРИГГЕРЫ ЗАПУСКА ---
# 1. АВТОМАТИЧЕСКИ: при пуше в основную ветку, если были изменены файлы
#    внутри папки `prompts/`.
# 2. ВРУЧНУЮ: через вкладку "Actions" в репозитории GitHub.
# ==============================================================================

name: Update Prompts Library

on:
  # 1. Запускать автоматически при любом изменении в папке prompts
  push:
    branches:
      - main # Укажите здесь вашу основную ветку (main или master)
    paths:
      - 'prompts/**'

  # 2. Позволяет запускать обновление вручную
  workflow_dispatch:

# --- ВАЖНО: ПРЕДОСТАВЛЕНИЕ ПРАВ ---
# Явно предоставляем права на запись в "contents" репозитория.
# Это необходимо для создания/обновления релизов и загрузки ассетов.
# Без этого блока будет ошибка 403 Forbidden.
permissions:
  contents: write

jobs:
  update_prompts_archive:
    name: Package and Update Prompts Archive
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Получаем код репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Создаем zip-архив с папкой prompts
      - name: Archive prompts directory
        run: zip -r prompts.zip ./prompts

      # Шаг 3: Обновляем ассет в "живом" релизе
      # Action `softprops/action-gh-release` сам найдет релиз по тегу,
      # создаст его, если не существует, и перезапишет ассеты с
      # тем же именем.
      - name: Update or Create Release with Prompts Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest-prompts # Стабильный тег, который мы будем использовать
          name: "Prompts Library (Latest)"
          body: "Автоматически обновляемая библиотека промптов. Этот релиз всегда содержит самую свежую версию."
          draft: false
          prerelease: false
          files: prompts.zip # Action найдет и перезапишет этот файл, если он уже существует
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # СИНХРОНИЗАЦИЯ С БАЗОЙ ДАННЫХ
      - name: Sync to Database with Chunked Upload
        run: |
          echo "🔄 Starting chunked sync at $(date)"

          # Размер чанка (количество файлов в одной порции)
          CHUNK_SIZE=50

          # Получаем список всех JSON файлов
          find prompts -name "*.json" > files_list.txt

          # Разбиваем на части и отправляем
          split -l $CHUNK_SIZE files_list.txt chunk_

          for chunk_file in chunk_*; do
              echo "📦 Processing chunk: $chunk_file"

              # Создаем JSON для текущего чанка
              TEMP_FILE=$(mktemp)
              while IFS= read -r file; do
                  cat "$file"
              done < "$chunk_file" | jq -s '.' > "$TEMP_FILE"

              # Создаем payload
              PAYLOAD_FILE=$(mktemp)
              echo "{\"prompts\": $(cat "$TEMP_FILE"), \"source\": \"github-action\", \"chunk\": \"$chunk_file\"}" > "$PAYLOAD_FILE"

              # Отправляем чанк
              HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
                -X POST "${{ secrets.SYNC_WEBHOOK_URL }}" \
                -H "Content-Type: application/json" \
                -H "X-API-Key: ${{ secrets.SYNC_API_KEY }}" \
                -d @"$PAYLOAD_FILE")

              # Очищаем временные файлы
              rm -f "$TEMP_FILE" "$PAYLOAD_FILE"

              # Проверяем результат
              if [ "$HTTP_STATUS" -ge 200 ] && [ "$HTTP_STATUS" -lt 300 ]; then
                  echo "✅ Chunk $chunk_file synced successfully (HTTP $HTTP_STATUS)"
              else
                  echo "❌ Chunk $chunk_file failed (HTTP $HTTP_STATUS)"
                  exit 1
              fi

              # Небольшая пауза между чанками
              sleep 1
          done

          # Очистка
          rm -f files_list.txt chunk_*

          echo "🟢 All chunks synced successfully at $(date)"
